### PR TITLE
docs: clarify that setCommits is not set by default

### LINKED ISSUE #372: Deprecated attachCommits actually still required
[Docs say not to use `attachCommits`](https://sentry.nuxtjs.org/sentry/options#attachcommits) but[ the code only uses the replacement `publishRelease.setCommits` when `attachCommits` is set](https://github.com/nuxt-community/sentry-module/blob/607511a4e4c6000fbea78e811249839d4a1f7272/lib/core/hooks.js#L222).

### PR DESCRIPTION
**Pull request by bmulholland**
Closes #372

### CODE REVIEW

**Comment by bmulholland** [comment]
Hold this - I'll fix the commit and add a note to be careful with nuxt/emotion

**Comment by bmulholland** [comment]
Okay this is good to go now.

**Comment by rchl** [comment]
I don't see any mention of nuxt/emotion. Did you decide against adding it?

**Comment by bmulholland** [comment]
See https://github.com/nuxt-community/sentry-module/discussions/369#discussioncomment-1694390

**Comment by rchl** [comment]
Thanks

**Pull request merged**
