### PR TITLE
use debug module like other nuxt packages

### PR DESCRIPTION
**Pull request by btkostner**
Before:
screenshot from 2018-07-05 16 01 47

After:
screenshot from 2018-07-05 16 02 44

### CODE REVIEW

**Comment by pi0** [comment]
Using consola with upcoming 2.0 release is more prefered. Nuxt and Some official modules already migrated too :)

**Comment by DiederikvandenB** [comment]
I'll look in to it after the weekend.

**Comment by DiederikvandenB** [comment]
@btkostner, are you willing to update your PR to use Consola?

**Comment by btkostner** [comment]
@DiederikvandenB sure

**Pull request merged**
