### PR TITLE
fix(tracing): connect backend and frontend traces

### LINKED ISSUE #500: Is perfomence monitoring really enabled on server?
[Documentation ](https://sentry.nuxtjs.org/sentry/options/#tracing) says that `tracing` option
> Enables Sentry Performance Monitoring on the [server](https://docs.sentry.io/platforms/node/performance/) and [browser](https://docs.sentry.io/platforms/javascript/guides/vue/performance/) side.

but I don't see any transaction from server side in sentry...

In sources I found [code](https://github.com/nuxt-community/sentry-module/blob/9614795af3a5aa9730a2fbf4346f1eb0f7010059/lib/core/hooks.js#L169-L170) which adds errorHandler and requestHandler, but [sentry documentation](https://docs.sentry.io/platforms/node/guides/express/performance/) for nodejs perfomence says we should use tracingHandler after requestHandler

Also [there is ability](https://docs.sentry.io/platforms/javascript/performance/connect-services/#pageload) to connect ssr with browser transaction throgh meta tags

### PR DESCRIPTION
**Pull request by rchl**
Resolves #500

### CODE REVIEW

**Comment by arkhamvm** [comment]
@rchl After updating from `7.1.3` to `7.1.5` server tracing in my project is gone. I tried `7.1.10` as well.

```
"@sentry/node": "7.45.0",
"@sentry/tracing": "7.45.0",
```

`['@nuxtjs/sentry', {ignore: ['node_modules']}],`

**Comment by rchl** [comment]
Revert module to `7.1.3` and check if it's working again.

**Comment by arkhamvm** [comment]
Reverted to `7.1.3` and it works.

**Comment by rchl** [comment]
You haven't given me a lot to work with but you can try to run with debug option enabled

```
sentry: {
  config: {
    debug: true
  }
}
```

and compare logs in the terminal with the working and non-working module versions.

**Comment by arkhamvm** [comment]
@rchl after many tests, I can't reproduce problem stable. Tracing randomly disappears after some rebuilds of project. 
`7.1.3` works stable. 

> You haven't given me a lot to work with

Of course I can send to you any info you needed.

> you can try to run with debug option enabled

In cases when traces doesn't sends, debug log is empty.
Can it be issue with `reducing bundle size` feature?

**Pull request merged**
