### PR TITLE
support nodejs server with production environment

### PR DESCRIPTION
**Pull request by abakermi**
#230

### CODE REVIEW

**Comment by rchl** [comment]
- Undocumented new option
 - Not respecting `moduleOptions` (options can come from it also)
 - Doesn't seem to be specific to the production environment like fix description says but to programmatic Nuxt usage
 - I'd prefer this to be handled automatically. Would it work to always init on `ready`?

**Review by rchl — CHANGES_REQUESTED** [review]
- Undocumented new option
 - Not respecting `moduleOptions` (options can come from it also)
 - Doesn't seem to be specific to the production environment like fix description says but to programmatic Nuxt usage
 - I'd prefer this to be handled automatically. Would it work to always init on `ready`?

**Comment by abakermi** [comment]
@rchl  `ready` should work well , I will document the option

**Comment by rchl** [comment]
There is no need to and the option in the first place if you are gonna use `ready` always.

**Comment by rchl** [comment]
Using `ready` would mean that Sentry would also be initialized when building the project. Not sure about that myself but I'd lean towards it being OK. @pimlie @pi0 any opinions?

**Comment by pi0** [comment]
Always using `ready` instead of `listen` (1) seems good idea  :+1:   We should just ensure to not double init on same node instance as `nuxt generate` with `target: 'static'` and cache (MISS) initializes nuxt twice once for build and once for generate.

Agree @rchl for going towards initializing sentry when building. But if not desired for any reason or is breaking change, we can use either `options._build` (2)  or `!options.server` to avoid initializing when building.

(1) I think `listenHook` name seems little bit misleading for source code as it [directly calls](https://github.com/nuxt-community/sentry-module/blob/c884b917249e784aaaae1a9d7bb186ba32df5d3a/lib/core/hooks.js#L211) `initSentry`

(2) As already mentioned, `options._*` flags are only prefixed to avoid conflicting with user options. You can safety rely on them :)

**Comment by rchl** [comment]
Thanks @pi0 for your input. I'm addressing this and your comments in https://github.com/nuxt-community/sentry-module/pull/235.

**Pull request closed without merging**
