### PR TITLE
fix(docs): fixes typography & content styling

### PR DESCRIPTION
**Pull request by aldy505**
This is what currenty [Sentry docs](https://sentry.nuxtjs.org/) shows:

Current docs

It turns out, on `@nuxt/content-theme-docs` `^0.10.0` and higher, the styling's broken. Reverting the version back to `^0.9.0` fixes the problem.

New docs

### CODE REVIEW

**Comment by rchl** [comment]
Thanks!

**Comment by rchl** [comment]
Thank didn't really fix anything, did it?

I think it's more about the sub dependencies of that package rather than the package version itself.

**Comment by aldy505** [comment]
It fixed the problem on my machine, installing nuxt/content v0.10.0 brokes the docs again on mine, I've tested it.

**Comment by rchl** [comment]
It's still broken on https://sentry.nuxtjs.org/
I'm fixing it with #291

As I said, it's not necessarily the version of nuxt/content that matters but one of the dependencies referenced in the lock file. So the nuxt/context version can be higher as long as that dependency is not updated. Not sure which one though.

**Pull request merged**
