### PR TITLE
fix: log state of the Sentry logging properly

### LINKED ISSUE #183: Contradicting log messages
When running sentry-module in dev mode it first logs:

> Errors will not be logged because no DSN has been provided

but immediately after that it logs
> Started logging errors to Sentry

See also: 
image

So which statement is true? ;)

### PR DESCRIPTION
**Pull request by rchl**
Resolves #183

### CODE REVIEW

**Comment by rchl** [comment]
I knew that. The thing is barely noticeable and easy to miss.
But I can remove it after all. I'm going back and forth on that.

**Comment by pimlie** [comment]
Maybe we could change the first part of the message to: `Errors won't be reported to Sentry because ${why}`

**Comment by rchl** [comment]
What do you think about what I did: `Sentry errors will not be logged because ...`?
I guess it's a bit broken grammar but my intention was to have "Sentry" at the beginning so that it's easy to scan where is the message from.

**Comment by pimlie** [comment]
What about `Sentry reporting is disabled because ...` or someting similar? Otherwise people could maybe think its just about errors caused by Sentry itself.

**Pull request merged**
