### PR TITLE
Unnecessary async removed

### PR DESCRIPTION
**Pull request by anteriovieira**

### CODE REVIEW

**Comment by anteriovieira** [comment]
cc @pi0

**Comment by DiederikvandenB** [comment]
I'll review and merge this tomorrow, just got back from a trip.

**Comment by dmitry-guryev** [comment]
Async makes this module incompatible with Node.js < 8

**Comment by DiederikvandenB** [comment]
Just merged and released. Since I don't have a lot of time today, @dmitry-guryev, could you check if the release resolves your issue? Thanks!

**Comment by dmitry-guryev** [comment]
It works, thank you!

**Pull request merged**
