### PR TITLE
fix: better handling of functions options in config

### LINKED ISSUE #266: Incorrect serialize sentry config (beforeSend)
### Version
@nuxtjs/sentry: 4.5.0
nuxt: 2.14.12

### Sentry configuration
```ts
  sentry: {
    dsn: 'https://examplePublicKey@o0.ingest.sentry.io/0', // Enter your project's DSN here
    config: {
      beforeSend(event, hint) {
        const ignoreErrorInBeforeSend = [
          {
            check: (event, hint) => {
              // Ignore fbevent.js postMessage error in iOS device
              if (hint?.originalException?.stack) {
                // eslint-disable-next-line dot-notation
                const errorStack = JSON.stringify(hint.originalException.stack)
                return /postMessage/.test(errorStack)
              }

              return false
            },
          },
        ]

        const shouldIgnoreError = ignoreErrorInBeforeSend.some((rule) =>
          rule.check(event, hint)
        )
        return shouldIgnoreError ? null : event
      },
    }, // Additional config
  },
```

### Reproduction Link
https://github.com/charlie0228/nuxt-sentry-issue

### Steps to reproduce
1. run `yarn build`
2. check `.nuxt\sentry.client.js`

### What is Expected?
Correct syntax in `.nuxt\sentry.client.js`
This issue is similar to #226 

### What is actually happening?
Incorrect config syntax like below, the `const config` is all wrong!

`.nuxt\sentry.client.js`
```ts
import VueLib from 'vue'
import * as Sentry from '@sentry/browser'

import { Dedupe, ExtraErrorData, ReportingObserver, RewriteFrames, Vue } from '@sentry/integrations'

export default function (ctx, inject) {
  /* eslint-disable object-curly-spacing, quote-props, quotes, key-spacing, comma-spacing */
  const config = {"dsn":"https:\u002F\u002FexamplePublicKey@o0.ingest.sentry.io\u002F0","environment":"production","beforeSend":beforeSend(event, hint) {
                const ignoreErrorInBeforeSend = [
                    {
                        check: (event, hint) => {
                            var _a;
                            // Ignore fbevent.js postMessage error in iOS device
                            if ((_a = hint === null || hint === void 0 ? void 0 : hint.originalException) === null || _a === void 0 ? void 0 : _a.stack) {
                                // eslint-disable-next-line dot-notation
                                const errorStack = JSON.stringify(hint.originalException.stack);
                                return /postMessage/.test(errorStack);
                            }
                            return false;
                        },
                    },
                ];
                const shouldIgnoreError = ignoreErrorInBeforeSend.some((rule) => rule.check(event, hint));
                return shouldIgnoreError ? null : event;
            }}
  config.integrations = [
    new Dedupe({}),
    new ExtraErrorData({}),
    new ReportingObserver({}),
    new RewriteFrames({}),
    new Vue({ Vue: VueLib, ...{"attachProps":true,"logErrors":false}})
  ]

  /* eslint-enable object-curly-spacing, quote-props, quotes, key-spacing, comma-spacing */
  Sentry.init(config)

  inject('sentry', Sentry)
  ctx.$sentry = Sentry
}
```

### PR DESCRIPTION
**Pull request by charlie0228**
Fixes #266 
Check config when the option is a function then using `serializeFunction(option)` instead of using `serialize(option)`

### CODE REVIEW

**Comment by guAnsunyata** [comment]
It works for me!

**Comment by rchl** [comment]
This doesn't seem to help.

With a configuration like:

```js
  sentry: {
    dsn: 'https://fe8b7df6ea7042f69d7a97c66c2934f7@sentry.io.nuxt/1429779',
    config: {
      beforeSend (event, hint) {
        const ignoreErrorInBeforeSend = [
          {
            check: (event, hint) => {
              // Ignore fbevent.js postMessage error in iOS device
              if (hint.originalException.stack) {
                // eslint-disable-next-line dot-notation
                const errorStack = JSON.stringify(hint.originalException.stack)
                return /postMessage/.test(errorStack)
              }

              return false
            }
          }
        ]

        const shouldIgnoreError = ignoreErrorInBeforeSend.some(rule =>
          rule.check(event, hint)
        )
        return shouldIgnoreError ? null : event
      }
    },
  }
```

it produces:

```js
  const config = {
    dsn:"https:\u002F\u002Ffe8b7df6ea7042f69d7a97c66c2934f7@sentry.io.nuxt\u002F1429779",
    environment:"development",
    beforeSend:beforeSend (event, hint) {
        const ignoreErrorInBeforeSend = [
          {
            check: (event, hint) => {
              // Ignore fbevent.js postMessage error in iOS device
              if (hint.originalException.stack) {
                // eslint-disable-next-line dot-notation
                const errorStack = JSON.stringify(hint.originalException.stack)
                return /postMessage/.test(errorStack)
              }

              return false
            }
          }
        ]

        const shouldIgnoreError = ignoreErrorInBeforeSend.some(rule =>
          rule.check(event, hint)
        )
        return shouldIgnoreError ? null : event
      },
    release:"a21baf77b07df7892b8dcac059ef4e39c53d5eb7"
  }
```

which is still invalid due to `beforeSend:beforeSend (event, hint) {` part. Should be `beforeSend:function (event, hint) {`

**Comment by charlie0228** [comment]
Thanks for your review!
Let me check my PR again.

**Comment by charlie0228** [comment]
> This doesn't seem to help.
> 
> With a configuration like:
> 
> ```js
>   sentry: {
>     dsn: 'https://fe8b7df6ea7042f69d7a97c66c2934f7@sentry.io.nuxt/1429779',
>     config: {
>       beforeSend (event, hint) {
>         const ignoreErrorInBeforeSend = [
>           {
>             check: (event, hint) => {
>               // Ignore fbevent.js postMessage error in iOS device
>               if (hint.originalException.stack) {
>                 // eslint-disable-next-line dot-notation
>                 const errorStack = JSON.stringify(hint.originalException.stack)
>                 return /postMessage/.test(errorStack)
>               }
> 
>               return false
>             }
>           }
>         ]
> 
>         const shouldIgnoreError = ignoreErrorInBeforeSend.some(rule =>
>           rule.check(event, hint)
>         )
>         return shouldIgnoreError ? null : event
>       }
>     },
>   }
> ```
> 
> it produces:
> 
> ```js
>   const config = {
>     dsn:"https:\u002F\u002Ffe8b7df6ea7042f69d7a97c66c2934f7@sentry.io.nuxt\u002F1429779",
>     environment:"development",
>     beforeSend:beforeSend (event, hint) {
>         const ignoreErrorInBeforeSend = [
>           {
>             check: (event, hint) => {
>               // Ignore fbevent.js postMessage error in iOS device
>               if (hint.originalException.stack) {
>                 // eslint-disable-next-line dot-notation
>                 const errorStack = JSON.stringify(hint.originalException.stack)
>                 return /postMessage/.test(errorStack)
>               }
> 
>               return false
>             }
>           }
>         ]
> 
>         const shouldIgnoreError = ignoreErrorInBeforeSend.some(rule =>
>           rule.check(event, hint)
>         )
>         return shouldIgnoreError ? null : event
>       },
>     release:"a21baf77b07df7892b8dcac059ef4e39c53d5eb7"
>   }
> ```
> 
> which is still invalid due to `beforeSend:beforeSend (event, hint) {` part. Should be `beforeSend:function (event, hint) {`

Sorry, may I ask you how to run the test?
Because I used the same config you paste above, I still got the correct result.

My result:
```js
  /* eslint-disable object-curly-spacing, quote-props, quotes, key-spacing, comma-spacing */
  const config = {
    dsn:"https:\u002F\u002Ffe8b7df6ea7042f69d7a97c66c2934f7@sentry.io.nuxt\u002F1429779",
    environment:"production",
    beforeSend:function (event, hint) {
                const ignoreErrorInBeforeSend = [
                    {
                        check: (event, hint) => {
                            // Ignore fbevent.js postMessage error in iOS device
                            if (hint.originalException.stack) {
                                // eslint-disable-next-line dot-notation
                                const errorStack = JSON.stringify(hint.originalException.stack);
                                return /postMessage/.test(errorStack);
                            }
                            return false;
                        }
                    }
                ];
                const shouldIgnoreError = ignoreErrorInBeforeSend.some(rule => rule.check(event, hint));
                return shouldIgnoreError ? null : event;
            },
    release:"b6fb6ef3295f635286d1df9db735a25f781000d5"
  }
```

I got correct `beforeSend:function (event, hint) {` result.

**Comment by rchl** [comment]
I'm testing on this repo itself with this change:

```diff
diff --git a/test/fixture/default/nuxt.config.js b/test/fixture/default/nuxt.config.js
index af2f3db..dc77268 100644
--- a/test/fixture/default/nuxt.config.js
+++ b/test/fixture/default/nuxt.config.js
@@ -17,7 +17,29 @@ const config = {
   ],
   sentry: {
     dsn: 'https://fe8b7df6ea7042f69d7a97c66c2934f7@sentry.io.nuxt/1429779',
-    config: {},
+    config: {
+      beforeSend (event, hint) {
+        const ignoreErrorInBeforeSend = [
+          {
+            check: (event, hint) => {
+              // Ignore fbevent.js postMessage error in iOS device
+              if (hint.originalException.stack) {
+                // eslint-disable-next-line dot-notation
+                const errorStack = JSON.stringify(hint.originalException.stack)
+                return /postMessage/.test(errorStack)
+              }
+
+              return false
+            }
+          }
+        ]
+
+        const shouldIgnoreError = ignoreErrorInBeforeSend.some(rule =>                                                                                                                                                                  
+          rule.check(event, hint)
+        )
+        return shouldIgnoreError ? null : event
+      }
+    },
     clientIntegrations: {
       // Integration from @Sentry/browser package.
       TryCatch: { eventTarget: false }
```

And then running `yarn dev:fixture`.
Then checking the generated file in `./test/fixture/default/.nuxt/sentry.client.js`

**Comment by charlie0228** [comment]
Thanks!
After some testing, I found the issue which mat related to `serializeFunction()`

With `beforeSend (event, hint) {`, the serialized result will be `beforeSend:beforeSend (event, hint) {`
However, with `beforeSend(event, hint) {` (without space between function name and left bracket), the serialized result will be `beforeSend:function (event, hint) {`, which is the correct result.

**Comment by rchl** [comment]
Sounds like a bug in `serializeFunction`. Will you handle that on the Nuxt side?

**Comment by charlie0228** [comment]
> Sounds like a bug in `serializeFunction`. Will you handle that on the Nuxt side?

Maybe I can try it, otherwise, I have to use some hack to fix this issue.

**Comment by eljass** [comment]
Any updates on this?

**Comment by rchl** [comment]
I found and fixed the Nuxt issue (https://github.com/nuxt/nuxt.js/issues/8779) so once the Nuxt fix is integrated this fix will work in more (all?) cases.

This fix is good in itself though and I will merge it soon.

**Comment by rchl** [comment]
BTW. I haven't tried, but it should be possible to use the [Runtime config](https://sentry.nuxtjs.org/sentry/runtime-config) to define `beforeSend` and avoid the original problem entirely.

**Comment by charlie0228** [comment]
> I found and fixed the Nuxt issue ([nuxt/nuxt.js#8779](https://github.com/nuxt/nuxt.js/issues/8779)) so once the Nuxt fix is integrated this fix will work in more (all?) cases.
> 
> This fix is good in itself though and I will merge it soon.

Thanks for helping!

**Pull request merged**
